# Generated by Django 5.2.1 on 2025-05-28 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=10, unique=True)),
                ('grade', models.CharField(max_length=10)),
                ('subgroup', models.CharField(max_length=50)),
                ('register_date', models.DateField()),
                ('deregister_date', models.DateField()),
                ('tan_khah_total', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='matched_student_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='price_per_person',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='subgroup_language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='StdEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_tag', models.CharField(max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.student')),
            ],
        ),
        migrations.CreateModel(
            name='TanKhahEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.student')),
            ],
        ),
    ]
