# Generated by Django 5.2.1 on 2025-05-31 09:58

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_student_invoiceitem_matched_student_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=django_jalali.db.models.jDateTimeField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='deregister_date',
            field=django_jalali.db.models.jDateTimeField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='register_date',
            field=django_jalali.db.models.jDateTimeField(),
        ),
    ]
