# Generated by Django 5.2.1 on 2025-05-31 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_alter_invoice_invoice_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateTimeField(null=True),
        ),
    ]
