# Generated by Django 5.2.1 on 2025-05-31 10:39

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_alter_invoice_invoice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=django_jalali.db.models.jDateField(),
        ),
    ]
