# Generated by Django 5.2.1 on 2025-06-01 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_alter_invoice_invoice_date'),
    ]

    operations = [
    ]
