# Generated by Django 5.2.1 on 2025-06-01 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_auto_20250601_0949'),
    ]

    operations = [
    ]
